### ISSUE TITLE
automate testing of drivers

### ISSUE THREAD

**Issue by johnscancella** [LibraryOfCongress/bagit-conformance-suite#4]
currently we have a make file for running the python implementation driver. It would ideal if we had some sort of automated testing for any number of drivers and for all versions (valid and invalid)

**Comment by acdha** [comment]
The counter-proposal I've been weighing is that we shouldn't have anything in this repo and should instead encourage upstream projects to check this repo out as part of their test suite (or use a submodule :fearful:) and invoke it in whatever manner fits best with their existing test infrastructure.

**Comment by johnscancella** [comment]
I would say 👍  for checking it out on a per project basis, but I think we should also have it run the java python ones directly since they are owned by the LoC

**Comment by acdha** [comment]
I consider this done as of https://github.com/LibraryOfCongress/bagit-conformance-suite/commit/b25843a3733b18acbb70bae9fbc7169992cd265b but how does that play with the bagit-java implementation? It basically assumes you have a command-line tool which returns 0 or 1 based on the validation status.

**Comment by johnscancella** [comment]
I created my own test suite based on this repo. So the logic goes, `clone this repo in bagit-java` then `run integration tests` assuming that all directories that are "invalid" should throw an error.
