### ISSUE TITLE
Confirm correct handling of out-of-scope file access

### ISSUE THREAD

**Issue by acdha** [LibraryOfCongress/bagit-conformance-suite#5]
We should have invalid bags testing the warnings about out-of-scope file paths:

https://tools.ietf.org/html/draft-kunze-bagit-14#section-6.1

This should include tests for a leading `/`, `../`, `~<username>/`, `C:\`, and [`\\?\` and `\\.\`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247).

**Comment by acdha** [comment]
Before closing this issue we should make sure we have fetch.txt counterparts for all of these checks

**Comment by johnscancella** [comment]
@acdha are we missing anything from this? Should we go ahead and close?

**Comment by acdha** [comment]
👍
