### ISSUE TITLE
manifest with a leading asterisk on a filename

### ISSUE THREAD

**Issue by acdha** [LibraryOfCongress/bagit-conformance-suite#6]
The spec allows `*FILENAME` for compatibility with the GNU coreutils *sum utilities. It's not a requirement so we might want to add a category of bags which are valid but should produce warning/linter messages about possible compatibility issues.

See https://github.com/LibraryOfCongress/bagit-java/issues/69

**Comment by johnscancella** [comment]
I would suggest we create another directory called `warning` which should contain bags that should generate warnings

**Comment by acdha** [comment]
That works for me
